### ISSUE TITLE
Updated fishing and resort photo text 

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#130]
Issues:

1. Updated photo text updates the admin site right away when preview is active. 
2. Update photo text, then approve in the preview, then go back and make another text edit of the same pic - no preview option is enabled. 
3. Photos keep switching order when updates are made. Can we keep these in the same place, its confusing to update the 4th pic and then all of a sudden its the first pic, then I approve the change and it goes back to the 4th pic...updates of an existing photo should stay in the same place, new pictures should be pushed to the first picture (so newest pic is first, oldest is last)

@bschmitz9 #3 is done here now.

**Comment by dolson334** [comment]
@bschmitz9 

1. I have to think on the best approach for this one.. But yes i will fix. 

2. I am pretty sure this is because after you approve the change and go back to the admin page you are still passing back the pageUpdates... so it approves again. I think you can fix this by clearing out the pageUpdates after the getPictures call. 

3. Yea I can fix this.

**Comment by dolson334** [comment]
@bschmitz9 

Ok a couple thing on #2.
 1) I am now passing back a param you can use to determine if updates were successful, it is an alert. 

 2) For updating a single change (so using the preview page) functions, if the update is successful and no pendingchanges exist you can just pass like "changesUpdated" as a query param to tell yourself everything has been approved on the admin site. 

3) The approve all is a little trickier since this button calls the admin service. Could we instead just call the main site "approvePictureUpdate" with a variable saying approveAll or something? Or maybe just create a new function that calls the getAllPictures? The you can just add params telling you things were success to the router navigate ("unitApproved", or "allUnitsApproved").

**Comment by bschmitz9** [comment]
@dolson334 response.updatesSuccessful is false when coming back to the admin page even tho the page is being updated with the new resort photo

**Comment by bschmitz9** [comment]
@dolson334 for #2, if they approve just one photo and there are no more pending changes they'll go to the admin site, so response.updatesSuccessful is all I'll need there. If they approve and there are still other pending changes, sounds like it works fine to just reload the preview page.

**Comment by bschmitz9** [comment]
@dolson334 I updated the approve and delete all to run through the main site page. So for resort photos I added an "approveAllPictures" function and a "deleteAllChanges" function. Approve all or delete all pending changes and then it will redirect them back to the admin site without any route parameters. I still need to the "response.updateSuccessful" property in the admin site to know if things were updated successfully.

**Comment by dolson334** [comment]
@bschmitz9 instead of having the response.updateSuccessful in the admin site.. just use the url parameter of like "allApproved"? The when we get to the admin site you can just check for this param in the url and then youll know. When in the admin site I dont know what has been approved.
