### ISSUE TITLE
Updating blog to have picture doesn't get added to stagedValues

### ISSUE THREAD

**Issue by bschmitz9** [dolson334/bantor#178]
If I try to add a picture to a blog that did not initially have a photo it doesn't get added to the stagedValues in the preview, therefore doesn't show the "Approve" button. 

Check this for stories and fishing reports as well as pictures are optional here as well.

**Comment by dolson334** [comment]
@bschmitz9 this is because from another ticket you wrote I no longer set IsPictureStaged if an object is IsNew. We can:

1. You can check for all pictures to see if any are IsNew on the blog.
2. I can add a new property on the backend called IsNewPicture which will state whether the blog has a new picture on it.

**Comment by dolson334** [comment]
@bschmitz9 this is working now for blog.. Ill check stories and fishing reports and write a new one up if needed.
