### ISSUE TITLE
Unit New Video Bug Pending Page

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#182]
Recreation:
1. Go to units
2. Add new mp4 and webm videos 
3. Go to pending page --> the video is not highlighted in red. 
--This is a new video so IsNew is true.

<img width="683" alt="videoNoRed" src="https://user-images.githubusercontent.com/16144247/54089983-153e9600-433d-11e9-83b3-e95f46cda424.png">
@bschmitz9

**Comment by bschmitz9** [comment]
@dolson334 looks like the issue here is there are two units in the videos array when I hit this page. The video that I deleted is still at videos[0] and isNew is false for this video. You need to make sure the deleted video is removed so the new video sits at the first position (i.e. videos[0]. 

I updated the html to look for isNew so this should work when you correct the array.

**Comment by dolson334** [comment]
@bschmitz9 working now
