### ISSUE TITLE
Setup admin home page

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#185]

**Comment by dolson334** [comment]
@bschmitz9 what is the plan for this page

**Comment by bschmitz9** [comment]
@dolson334 can you set up the endpoints for this page with the token so the page doesn't break? Right now getStories is the end point so that'll need to be updated to something else. Basically this page just allows them to update the top section of their home page - the background image and the company slogan. So in the response you just need to send back those two things along with the resort name. Just get the response back and then push.

**Comment by dolson334** [comment]
@bschmitz9 this info should now be loading. There is an html error. Ill let you look into that... I think you need an ngIf in there somewhere.

**Comment by bschmitz9** [comment]
@dolson334 ok you should be able to save the updates to the database now and then show the preview. Right now "isHomeInfoStaged" is hard coded to true in the admin, needs to be setup to come from the database. Also, when I go to preview the home page and click the "Back to Admin" button it brings me back to the login screen. But it doesn't do that for the other pages..assuming the token needs to be set up for this page?

I think we can just do "Approve All Updates" as the only option here since its only the slogan and the background image.

**Comment by dolson334** [comment]
@bschmitz9 Along with the base64 string can you also return the pictureId when a picture is modified on admin page?

**Comment by bschmitz9** [comment]
@dolson334 I don't know if you're asking me a question or what but you shouldn't need an ID there. You already know what photo it is if its coming through that endpoint - "home-background". You can pass that string in in the endpoint call from home.service.

But if you want the id let me know how I can get it and I can pass it back to the edit modal.

**Comment by dolson334** [comment]
@bschmitz9 yes thats what I want. The picture that we are editings Id.

**Comment by bschmitz9** [comment]
@dolson334 ok how do I get it? Not sure with all those functions.

**Comment by dolson334** [comment]
@bschmitz9 its on the picture object. You do it in other edit modals.

**Comment by dolson334** [comment]
@bschmitz9 or the photo object I should say in javascript.

**Comment by bschmitz9** [comment]
@dolson334 ok I pushed it. They make use this photo other places in the site too so make sure you aren't updating this picture other places in the site. Only the home page background image.
