### ISSUE TITLE
AboutUs Features Detailed Picture Bug

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#274]
Recreation
Update a features details picture --> all features detailed are gone on the admin site

**Comment by bschmitz9** [comment]
@dolson334 this is happening because right now I have an *ngIf on that section to make sure there is a feature uploaded to make sure we want to show that section:

`*ngIf="aboutUsFeaturesDetailed1.picture.dir && aboutUsFeaturesDetailed1.title.text && aboutUsFeaturesDetailed1.summary.text"`

When I update a picture and the page reloads the picture object comes back as false. I'm using the old getPicture function you made a while back. It works before you change the picture. Check it out.
