### ISSUE TITLE
Unstaging Json Values

### ISSUE THREAD

**Issue by dolson334** [dolson334/bantor#291]
@bschmitz9 

Could you return everything in this format. If so we could get rid of a ton of code. This is basically a piece of what you are already returning reformatted.  I wouldnt need the section or anything. Essentially, I can just loop through and unstage everything in the "objects" array (I already have this backend code built). This example is what the employees intro approval in aboutUs would look like. This way things wont break when we rename stuff since the id will be the same. We need to do this. 

```

{
  "objects": [
    {
      "isVideoStaged": false,
      "stagedValues": {
        "text": "222222"
      },
      "log": "java.util.logging.Logger@7f47093",
      "isPictureStaged": false,
      "isStaged": true,
      "videos": [],
      "id": 3,
      "isNew": false,
      "objectMetaType": "resort",
      "text": "Lorem, ipsum dolor sit amet consectetur     adipisicing elit. Dolores animi placeat 
        nostrum   sint laudantium esse quos officia. Lorem, ipsum   dolor sit amet consectetur 
         adipisicing elit.     Dolores animi placeat nostrum sint laudantium    esse quos officia.",
      "key": "aboutUsEmployeesIntroParagraph",
      "objectType": "PAGE_TEXT"
    },
    {
      "isVideoStaged": false,
      "stagedValues": {
        "text": "11111"
      },
      "log": "java.util.logging.Logger@7f47093",
      "isPictureStaged": false,
      "isStaged": true,
      "videos": [],
      "id": 2,
      "isNew": false,
      "objectMetaType": "resort",
      "text": "Employee Intro Header",
      "key": "aboutUsEmployeesIntroHeader",
      "objectType": "PAGE_TEXT"
    }
  ]
}
```

**Comment by bschmitz9** [comment]
@dolson334 I think database should be organized with this format, not reformatted on the front end.  So that when the aboutUsPage loads and goes to the endpoint your query brings back the AboutUs header info back with this format. Then that object can be passed to the front end and then to the back end when updates are made. That way you save code and I save code. I could get rid of all of that getTextObject function and just bind directly from the response. Right now I have to get everything through the key.

It's just going to add more code on my end if I have to get the text object and then reformat it. The format you have above would make it much easier on my end as well.

**Comment by bschmitz9** [comment]
@dolson334 I can look into this but ideally this would come right from the database just like you have. That way we both save code. I can get rid of all of those getTextObject function calls.

**Comment by dolson334** [comment]
@bschmitz9 it should already be doing this. What I have above is what I copied from some of your "selected" jsons

**Comment by dolson334** [comment]
@bschmitz9 did u do this yet?

**Comment by bschmitz9** [comment]
@dolson334 you can try this now for the about us section intros in the main site / preview . title and summary are now in an array.

**Comment by dolson334** [comment]
@bschmitz9 works great. keep putting the objects in the "section" array. I have this working for the intro section. Let me know when the others are ready. Will take me 2 seconds to make back end changes (if any needed at all).

Use the branch called "UnstagingValues".
